// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: query/contact_query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContactUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactUserListRequest) Reset() {
	*x = GetContactUserListRequest{}
	mi := &file_query_contact_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactUserListRequest) ProtoMessage() {}

func (x *GetContactUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactUserListRequest.ProtoReflect.Descriptor instead.
func (*GetContactUserListRequest) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetContactUserListRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type LoadMyJoinedGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMyJoinedGroupRequest) Reset() {
	*x = LoadMyJoinedGroupRequest{}
	mi := &file_query_contact_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMyJoinedGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMyJoinedGroupRequest) ProtoMessage() {}

func (x *LoadMyJoinedGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMyJoinedGroupRequest.ProtoReflect.Descriptor instead.
func (*LoadMyJoinedGroupRequest) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{1}
}

func (x *LoadMyJoinedGroupRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetContactInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactInfoRequest) Reset() {
	*x = GetContactInfoRequest{}
	mi := &file_query_contact_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactInfoRequest) ProtoMessage() {}

func (x *GetContactInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactInfoRequest.ProtoReflect.Descriptor instead.
func (*GetContactInfoRequest) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{2}
}

func (x *GetContactInfoRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type GetNewContactListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewContactListRequest) Reset() {
	*x = GetNewContactListRequest{}
	mi := &file_query_contact_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewContactListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewContactListRequest) ProtoMessage() {}

func (x *GetNewContactListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewContactListRequest.ProtoReflect.Descriptor instead.
func (*GetNewContactListRequest) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetNewContactListRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetAddGroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddGroupListRequest) Reset() {
	*x = GetAddGroupListRequest{}
	mi := &file_query_contact_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddGroupListRequest) ProtoMessage() {}

func (x *GetAddGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddGroupListRequest.ProtoReflect.Descriptor instead.
func (*GetAddGroupListRequest) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddGroupListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type MyUserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyUserItem) Reset() {
	*x = MyUserItem{}
	mi := &file_query_contact_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyUserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUserItem) ProtoMessage() {}

func (x *MyUserItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUserItem.ProtoReflect.Descriptor instead.
func (*MyUserItem) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{5}
}

func (x *MyUserItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MyUserItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MyUserItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetContactUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*MyUserItem          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactUserListResponse) Reset() {
	*x = GetContactUserListResponse{}
	mi := &file_query_contact_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactUserListResponse) ProtoMessage() {}

func (x *GetContactUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactUserListResponse.ProtoReflect.Descriptor instead.
func (*GetContactUserListResponse) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{6}
}

func (x *GetContactUserListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContactUserListResponse) GetList() []*MyUserItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetContactUserListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type JoinedGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinedGroupItem) Reset() {
	*x = JoinedGroupItem{}
	mi := &file_query_contact_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinedGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedGroupItem) ProtoMessage() {}

func (x *JoinedGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedGroupItem.ProtoReflect.Descriptor instead.
func (*JoinedGroupItem) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{7}
}

func (x *JoinedGroupItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinedGroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *JoinedGroupItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LoadMyJoinedGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*JoinedGroupItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMyJoinedGroupResponse) Reset() {
	*x = LoadMyJoinedGroupResponse{}
	mi := &file_query_contact_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMyJoinedGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMyJoinedGroupResponse) ProtoMessage() {}

func (x *LoadMyJoinedGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMyJoinedGroupResponse.ProtoReflect.Descriptor instead.
func (*LoadMyJoinedGroupResponse) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{8}
}

func (x *LoadMyJoinedGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadMyJoinedGroupResponse) GetList() []*JoinedGroupItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *LoadMyJoinedGroupResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type ContactInfoDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContactId        string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactName      string                 `protobuf:"bytes,2,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactAvatar    string                 `protobuf:"bytes,3,opt,name=contact_avatar,json=contactAvatar,proto3" json:"contact_avatar,omitempty"`
	ContactPhone     string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail     string                 `protobuf:"bytes,5,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactGender    int32                  `protobuf:"varint,6,opt,name=contact_gender,json=contactGender,proto3" json:"contact_gender,omitempty"`
	ContactSignature string                 `protobuf:"bytes,7,opt,name=contact_signature,json=contactSignature,proto3" json:"contact_signature,omitempty"`
	ContactBirthday  string                 `protobuf:"bytes,8,opt,name=contact_birthday,json=contactBirthday,proto3" json:"contact_birthday,omitempty"`
	ContactNotice    string                 `protobuf:"bytes,9,opt,name=contact_notice,json=contactNotice,proto3" json:"contact_notice,omitempty"`
	ContactMembers   []byte                 `protobuf:"bytes,10,opt,name=contact_members,json=contactMembers,proto3" json:"contact_members,omitempty"`
	ContactMemberCnt int32                  `protobuf:"varint,11,opt,name=contact_member_cnt,json=contactMemberCnt,proto3" json:"contact_member_cnt,omitempty"`
	ContactOwnerId   string                 `protobuf:"bytes,12,opt,name=contact_owner_id,json=contactOwnerId,proto3" json:"contact_owner_id,omitempty"`
	ContactAddMode   int32                  `protobuf:"varint,13,opt,name=contact_add_mode,json=contactAddMode,proto3" json:"contact_add_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContactInfoDetail) Reset() {
	*x = ContactInfoDetail{}
	mi := &file_query_contact_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfoDetail) ProtoMessage() {}

func (x *ContactInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfoDetail.ProtoReflect.Descriptor instead.
func (*ContactInfoDetail) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{9}
}

func (x *ContactInfoDetail) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *ContactInfoDetail) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *ContactInfoDetail) GetContactAvatar() string {
	if x != nil {
		return x.ContactAvatar
	}
	return ""
}

func (x *ContactInfoDetail) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *ContactInfoDetail) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *ContactInfoDetail) GetContactGender() int32 {
	if x != nil {
		return x.ContactGender
	}
	return 0
}

func (x *ContactInfoDetail) GetContactSignature() string {
	if x != nil {
		return x.ContactSignature
	}
	return ""
}

func (x *ContactInfoDetail) GetContactBirthday() string {
	if x != nil {
		return x.ContactBirthday
	}
	return ""
}

func (x *ContactInfoDetail) GetContactNotice() string {
	if x != nil {
		return x.ContactNotice
	}
	return ""
}

func (x *ContactInfoDetail) GetContactMembers() []byte {
	if x != nil {
		return x.ContactMembers
	}
	return nil
}

func (x *ContactInfoDetail) GetContactMemberCnt() int32 {
	if x != nil {
		return x.ContactMemberCnt
	}
	return 0
}

func (x *ContactInfoDetail) GetContactOwnerId() string {
	if x != nil {
		return x.ContactOwnerId
	}
	return ""
}

func (x *ContactInfoDetail) GetContactAddMode() int32 {
	if x != nil {
		return x.ContactAddMode
	}
	return 0
}

type GetContactInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Info          *ContactInfoDetail     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactInfoResponse) Reset() {
	*x = GetContactInfoResponse{}
	mi := &file_query_contact_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactInfoResponse) ProtoMessage() {}

func (x *GetContactInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactInfoResponse.ProtoReflect.Descriptor instead.
func (*GetContactInfoResponse) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{10}
}

func (x *GetContactInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetContactInfoResponse) GetInfo() *ContactInfoDetail {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetContactInfoResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type NewContactItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactName   string                 `protobuf:"bytes,2,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactAvatar string                 `protobuf:"bytes,3,opt,name=contact_avatar,json=contactAvatar,proto3" json:"contact_avatar,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewContactItem) Reset() {
	*x = NewContactItem{}
	mi := &file_query_contact_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewContactItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContactItem) ProtoMessage() {}

func (x *NewContactItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContactItem.ProtoReflect.Descriptor instead.
func (*NewContactItem) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{11}
}

func (x *NewContactItem) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *NewContactItem) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *NewContactItem) GetContactAvatar() string {
	if x != nil {
		return x.ContactAvatar
	}
	return ""
}

func (x *NewContactItem) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetNewContactListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*NewContactItem      `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewContactListResponse) Reset() {
	*x = GetNewContactListResponse{}
	mi := &file_query_contact_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewContactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewContactListResponse) ProtoMessage() {}

func (x *GetNewContactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewContactListResponse.ProtoReflect.Descriptor instead.
func (*GetNewContactListResponse) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{12}
}

func (x *GetNewContactListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetNewContactListResponse) GetList() []*NewContactItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetNewContactListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type AddGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	ContactName   string                 `protobuf:"bytes,2,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactAvatar string                 `protobuf:"bytes,3,opt,name=contact_avatar,json=contactAvatar,proto3" json:"contact_avatar,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupItem) Reset() {
	*x = AddGroupItem{}
	mi := &file_query_contact_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupItem) ProtoMessage() {}

func (x *AddGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupItem.ProtoReflect.Descriptor instead.
func (*AddGroupItem) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{13}
}

func (x *AddGroupItem) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *AddGroupItem) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *AddGroupItem) GetContactAvatar() string {
	if x != nil {
		return x.ContactAvatar
	}
	return ""
}

func (x *AddGroupItem) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetAddGroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*AddGroupItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddGroupListResponse) Reset() {
	*x = GetAddGroupListResponse{}
	mi := &file_query_contact_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddGroupListResponse) ProtoMessage() {}

func (x *GetAddGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_contact_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddGroupListResponse.ProtoReflect.Descriptor instead.
func (*GetAddGroupListResponse) Descriptor() ([]byte, []int) {
	return file_query_contact_query_proto_rawDescGZIP(), []int{14}
}

func (x *GetAddGroupListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAddGroupListResponse) GetList() []*AddGroupItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetAddGroupListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_query_contact_query_proto protoreflect.FileDescriptor

const file_query_contact_query_proto_rawDesc = "" +
	"\n" +
	"\x19query/contact_query.proto\x12\x05query\"6\n" +
	"\x19GetContactUserListRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"5\n" +
	"\x18LoadMyJoinedGroupRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"6\n" +
	"\x15GetContactInfoRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\"5\n" +
	"\x18GetNewContactListRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"3\n" +
	"\x16GetAddGroupListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"Z\n" +
	"\n" +
	"MyUserItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"o\n" +
	"\x1aGetContactUserListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x04list\x18\x02 \x03(\v2\x11.query.MyUserItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"c\n" +
	"\x0fJoinedGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"s\n" +
	"\x19LoadMyJoinedGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.query.JoinedGroupItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\x97\x04\n" +
	"\x11ContactInfoDetail\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12!\n" +
	"\fcontact_name\x18\x02 \x01(\tR\vcontactName\x12%\n" +
	"\x0econtact_avatar\x18\x03 \x01(\tR\rcontactAvatar\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\x05 \x01(\tR\fcontactEmail\x12%\n" +
	"\x0econtact_gender\x18\x06 \x01(\x05R\rcontactGender\x12+\n" +
	"\x11contact_signature\x18\a \x01(\tR\x10contactSignature\x12)\n" +
	"\x10contact_birthday\x18\b \x01(\tR\x0fcontactBirthday\x12%\n" +
	"\x0econtact_notice\x18\t \x01(\tR\rcontactNotice\x12'\n" +
	"\x0fcontact_members\x18\n" +
	" \x01(\fR\x0econtactMembers\x12,\n" +
	"\x12contact_member_cnt\x18\v \x01(\x05R\x10contactMemberCnt\x12(\n" +
	"\x10contact_owner_id\x18\f \x01(\tR\x0econtactOwnerId\x12(\n" +
	"\x10contact_add_mode\x18\r \x01(\x05R\x0econtactAddMode\"r\n" +
	"\x16GetContactInfoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\x04info\x18\x02 \x01(\v2\x18.query.ContactInfoDetailR\x04info\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\x8b\x01\n" +
	"\x0eNewContactItem\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12!\n" +
	"\fcontact_name\x18\x02 \x01(\tR\vcontactName\x12%\n" +
	"\x0econtact_avatar\x18\x03 \x01(\tR\rcontactAvatar\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"r\n" +
	"\x19GetNewContactListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.query.NewContactItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\x89\x01\n" +
	"\fAddGroupItem\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12!\n" +
	"\fcontact_name\x18\x02 \x01(\tR\vcontactName\x12%\n" +
	"\x0econtact_avatar\x18\x03 \x01(\tR\rcontactAvatar\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"n\n" +
	"\x17GetAddGroupListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x04list\x18\x02 \x03(\v2\x13.query.AddGroupItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret2\xba\x03\n" +
	"\x13ContactQueryService\x12R\n" +
	"\vGetUserList\x12 .query.GetContactUserListRequest\x1a!.query.GetContactUserListResponse\x12V\n" +
	"\x11LoadMyJoinedGroup\x12\x1f.query.LoadMyJoinedGroupRequest\x1a .query.LoadMyJoinedGroupResponse\x12M\n" +
	"\x0eGetContactInfo\x12\x1c.query.GetContactInfoRequest\x1a\x1d.query.GetContactInfoResponse\x12V\n" +
	"\x11GetNewContactList\x12\x1f.query.GetNewContactListRequest\x1a .query.GetNewContactListResponse\x12P\n" +
	"\x0fGetAddGroupList\x12\x1d.query.GetAddGroupListRequest\x1a\x1e.query.GetAddGroupListResponseB\x1eZ\x1ckama_chat_server/proto/queryb\x06proto3"

var (
	file_query_contact_query_proto_rawDescOnce sync.Once
	file_query_contact_query_proto_rawDescData []byte
)

func file_query_contact_query_proto_rawDescGZIP() []byte {
	file_query_contact_query_proto_rawDescOnce.Do(func() {
		file_query_contact_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_contact_query_proto_rawDesc), len(file_query_contact_query_proto_rawDesc)))
	})
	return file_query_contact_query_proto_rawDescData
}

var file_query_contact_query_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_query_contact_query_proto_goTypes = []any{
	(*GetContactUserListRequest)(nil),  // 0: query.GetContactUserListRequest
	(*LoadMyJoinedGroupRequest)(nil),   // 1: query.LoadMyJoinedGroupRequest
	(*GetContactInfoRequest)(nil),      // 2: query.GetContactInfoRequest
	(*GetNewContactListRequest)(nil),   // 3: query.GetNewContactListRequest
	(*GetAddGroupListRequest)(nil),     // 4: query.GetAddGroupListRequest
	(*MyUserItem)(nil),                 // 5: query.MyUserItem
	(*GetContactUserListResponse)(nil), // 6: query.GetContactUserListResponse
	(*JoinedGroupItem)(nil),            // 7: query.JoinedGroupItem
	(*LoadMyJoinedGroupResponse)(nil),  // 8: query.LoadMyJoinedGroupResponse
	(*ContactInfoDetail)(nil),          // 9: query.ContactInfoDetail
	(*GetContactInfoResponse)(nil),     // 10: query.GetContactInfoResponse
	(*NewContactItem)(nil),             // 11: query.NewContactItem
	(*GetNewContactListResponse)(nil),  // 12: query.GetNewContactListResponse
	(*AddGroupItem)(nil),               // 13: query.AddGroupItem
	(*GetAddGroupListResponse)(nil),    // 14: query.GetAddGroupListResponse
}
var file_query_contact_query_proto_depIdxs = []int32{
	5,  // 0: query.GetContactUserListResponse.list:type_name -> query.MyUserItem
	7,  // 1: query.LoadMyJoinedGroupResponse.list:type_name -> query.JoinedGroupItem
	9,  // 2: query.GetContactInfoResponse.info:type_name -> query.ContactInfoDetail
	11, // 3: query.GetNewContactListResponse.list:type_name -> query.NewContactItem
	13, // 4: query.GetAddGroupListResponse.list:type_name -> query.AddGroupItem
	0,  // 5: query.ContactQueryService.GetUserList:input_type -> query.GetContactUserListRequest
	1,  // 6: query.ContactQueryService.LoadMyJoinedGroup:input_type -> query.LoadMyJoinedGroupRequest
	2,  // 7: query.ContactQueryService.GetContactInfo:input_type -> query.GetContactInfoRequest
	3,  // 8: query.ContactQueryService.GetNewContactList:input_type -> query.GetNewContactListRequest
	4,  // 9: query.ContactQueryService.GetAddGroupList:input_type -> query.GetAddGroupListRequest
	6,  // 10: query.ContactQueryService.GetUserList:output_type -> query.GetContactUserListResponse
	8,  // 11: query.ContactQueryService.LoadMyJoinedGroup:output_type -> query.LoadMyJoinedGroupResponse
	10, // 12: query.ContactQueryService.GetContactInfo:output_type -> query.GetContactInfoResponse
	12, // 13: query.ContactQueryService.GetNewContactList:output_type -> query.GetNewContactListResponse
	14, // 14: query.ContactQueryService.GetAddGroupList:output_type -> query.GetAddGroupListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_query_contact_query_proto_init() }
func file_query_contact_query_proto_init() {
	if File_query_contact_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_contact_query_proto_rawDesc), len(file_query_contact_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_contact_query_proto_goTypes,
		DependencyIndexes: file_query_contact_query_proto_depIdxs,
		MessageInfos:      file_query_contact_query_proto_msgTypes,
	}.Build()
	File_query_contact_query_proto = out.File
	file_query_contact_query_proto_goTypes = nil
	file_query_contact_query_proto_depIdxs = nil
}
