// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: query/contact_query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContactQueryService_GetUserList_FullMethodName       = "/query.ContactQueryService/GetUserList"
	ContactQueryService_LoadMyJoinedGroup_FullMethodName = "/query.ContactQueryService/LoadMyJoinedGroup"
	ContactQueryService_GetContactInfo_FullMethodName    = "/query.ContactQueryService/GetContactInfo"
	ContactQueryService_GetNewContactList_FullMethodName = "/query.ContactQueryService/GetNewContactList"
	ContactQueryService_GetAddGroupList_FullMethodName   = "/query.ContactQueryService/GetAddGroupList"
)

// ContactQueryServiceClient is the client API for ContactQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContactQueryServiceClient interface {
	GetUserList(ctx context.Context, in *GetContactUserListRequest, opts ...grpc.CallOption) (*GetContactUserListResponse, error)
	LoadMyJoinedGroup(ctx context.Context, in *LoadMyJoinedGroupRequest, opts ...grpc.CallOption) (*LoadMyJoinedGroupResponse, error)
	GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*GetContactInfoResponse, error)
	GetNewContactList(ctx context.Context, in *GetNewContactListRequest, opts ...grpc.CallOption) (*GetNewContactListResponse, error)
	GetAddGroupList(ctx context.Context, in *GetAddGroupListRequest, opts ...grpc.CallOption) (*GetAddGroupListResponse, error)
}

type contactQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContactQueryServiceClient(cc grpc.ClientConnInterface) ContactQueryServiceClient {
	return &contactQueryServiceClient{cc}
}

func (c *contactQueryServiceClient) GetUserList(ctx context.Context, in *GetContactUserListRequest, opts ...grpc.CallOption) (*GetContactUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContactUserListResponse)
	err := c.cc.Invoke(ctx, ContactQueryService_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactQueryServiceClient) LoadMyJoinedGroup(ctx context.Context, in *LoadMyJoinedGroupRequest, opts ...grpc.CallOption) (*LoadMyJoinedGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadMyJoinedGroupResponse)
	err := c.cc.Invoke(ctx, ContactQueryService_LoadMyJoinedGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactQueryServiceClient) GetContactInfo(ctx context.Context, in *GetContactInfoRequest, opts ...grpc.CallOption) (*GetContactInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContactInfoResponse)
	err := c.cc.Invoke(ctx, ContactQueryService_GetContactInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactQueryServiceClient) GetNewContactList(ctx context.Context, in *GetNewContactListRequest, opts ...grpc.CallOption) (*GetNewContactListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewContactListResponse)
	err := c.cc.Invoke(ctx, ContactQueryService_GetNewContactList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactQueryServiceClient) GetAddGroupList(ctx context.Context, in *GetAddGroupListRequest, opts ...grpc.CallOption) (*GetAddGroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddGroupListResponse)
	err := c.cc.Invoke(ctx, ContactQueryService_GetAddGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactQueryServiceServer is the server API for ContactQueryService service.
// All implementations must embed UnimplementedContactQueryServiceServer
// for forward compatibility.
type ContactQueryServiceServer interface {
	GetUserList(context.Context, *GetContactUserListRequest) (*GetContactUserListResponse, error)
	LoadMyJoinedGroup(context.Context, *LoadMyJoinedGroupRequest) (*LoadMyJoinedGroupResponse, error)
	GetContactInfo(context.Context, *GetContactInfoRequest) (*GetContactInfoResponse, error)
	GetNewContactList(context.Context, *GetNewContactListRequest) (*GetNewContactListResponse, error)
	GetAddGroupList(context.Context, *GetAddGroupListRequest) (*GetAddGroupListResponse, error)
	mustEmbedUnimplementedContactQueryServiceServer()
}

// UnimplementedContactQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContactQueryServiceServer struct{}

func (UnimplementedContactQueryServiceServer) GetUserList(context.Context, *GetContactUserListRequest) (*GetContactUserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedContactQueryServiceServer) LoadMyJoinedGroup(context.Context, *LoadMyJoinedGroupRequest) (*LoadMyJoinedGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadMyJoinedGroup not implemented")
}
func (UnimplementedContactQueryServiceServer) GetContactInfo(context.Context, *GetContactInfoRequest) (*GetContactInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContactInfo not implemented")
}
func (UnimplementedContactQueryServiceServer) GetNewContactList(context.Context, *GetNewContactListRequest) (*GetNewContactListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewContactList not implemented")
}
func (UnimplementedContactQueryServiceServer) GetAddGroupList(context.Context, *GetAddGroupListRequest) (*GetAddGroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAddGroupList not implemented")
}
func (UnimplementedContactQueryServiceServer) mustEmbedUnimplementedContactQueryServiceServer() {}
func (UnimplementedContactQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeContactQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContactQueryServiceServer will
// result in compilation errors.
type UnsafeContactQueryServiceServer interface {
	mustEmbedUnimplementedContactQueryServiceServer()
}

func RegisterContactQueryServiceServer(s grpc.ServiceRegistrar, srv ContactQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedContactQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContactQueryService_ServiceDesc, srv)
}

func _ContactQueryService_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactQueryServiceServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactQueryService_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactQueryServiceServer).GetUserList(ctx, req.(*GetContactUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactQueryService_LoadMyJoinedGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMyJoinedGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactQueryServiceServer).LoadMyJoinedGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactQueryService_LoadMyJoinedGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactQueryServiceServer).LoadMyJoinedGroup(ctx, req.(*LoadMyJoinedGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactQueryService_GetContactInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactQueryServiceServer).GetContactInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactQueryService_GetContactInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactQueryServiceServer).GetContactInfo(ctx, req.(*GetContactInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactQueryService_GetNewContactList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewContactListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactQueryServiceServer).GetNewContactList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactQueryService_GetNewContactList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactQueryServiceServer).GetNewContactList(ctx, req.(*GetNewContactListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactQueryService_GetAddGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactQueryServiceServer).GetAddGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContactQueryService_GetAddGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactQueryServiceServer).GetAddGroupList(ctx, req.(*GetAddGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContactQueryService_ServiceDesc is the grpc.ServiceDesc for ContactQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContactQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.ContactQueryService",
	HandlerType: (*ContactQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserList",
			Handler:    _ContactQueryService_GetUserList_Handler,
		},
		{
			MethodName: "LoadMyJoinedGroup",
			Handler:    _ContactQueryService_LoadMyJoinedGroup_Handler,
		},
		{
			MethodName: "GetContactInfo",
			Handler:    _ContactQueryService_GetContactInfo_Handler,
		},
		{
			MethodName: "GetNewContactList",
			Handler:    _ContactQueryService_GetNewContactList_Handler,
		},
		{
			MethodName: "GetAddGroupList",
			Handler:    _ContactQueryService_GetAddGroupList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/contact_query.proto",
}
