// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: query/group_query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupQueryService_LoadMyGroup_FullMethodName        = "/query.GroupQueryService/LoadMyGroup"
	GroupQueryService_CheckGroupAddMode_FullMethodName  = "/query.GroupQueryService/CheckGroupAddMode"
	GroupQueryService_GetGroupInfo_FullMethodName       = "/query.GroupQueryService/GetGroupInfo"
	GroupQueryService_GetGroupInfoList_FullMethodName   = "/query.GroupQueryService/GetGroupInfoList"
	GroupQueryService_GetGroupMemberList_FullMethodName = "/query.GroupQueryService/GetGroupMemberList"
)

// GroupQueryServiceClient is the client API for GroupQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupQueryServiceClient interface {
	LoadMyGroup(ctx context.Context, in *LoadMyGroupRequest, opts ...grpc.CallOption) (*LoadMyGroupResponse, error)
	CheckGroupAddMode(ctx context.Context, in *CheckGroupAddModeRequest, opts ...grpc.CallOption) (*CheckGroupAddModeResponse, error)
	GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error)
	GetGroupInfoList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGroupInfoListResponse, error)
	GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GetGroupMemberListResponse, error)
}

type groupQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupQueryServiceClient(cc grpc.ClientConnInterface) GroupQueryServiceClient {
	return &groupQueryServiceClient{cc}
}

func (c *groupQueryServiceClient) LoadMyGroup(ctx context.Context, in *LoadMyGroupRequest, opts ...grpc.CallOption) (*LoadMyGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadMyGroupResponse)
	err := c.cc.Invoke(ctx, GroupQueryService_LoadMyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupQueryServiceClient) CheckGroupAddMode(ctx context.Context, in *CheckGroupAddModeRequest, opts ...grpc.CallOption) (*CheckGroupAddModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckGroupAddModeResponse)
	err := c.cc.Invoke(ctx, GroupQueryService_CheckGroupAddMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupQueryServiceClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoResponse)
	err := c.cc.Invoke(ctx, GroupQueryService_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupQueryServiceClient) GetGroupInfoList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetGroupInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoListResponse)
	err := c.cc.Invoke(ctx, GroupQueryService_GetGroupInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupQueryServiceClient) GetGroupMemberList(ctx context.Context, in *GetGroupMemberListRequest, opts ...grpc.CallOption) (*GetGroupMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMemberListResponse)
	err := c.cc.Invoke(ctx, GroupQueryService_GetGroupMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupQueryServiceServer is the server API for GroupQueryService service.
// All implementations must embed UnimplementedGroupQueryServiceServer
// for forward compatibility.
type GroupQueryServiceServer interface {
	LoadMyGroup(context.Context, *LoadMyGroupRequest) (*LoadMyGroupResponse, error)
	CheckGroupAddMode(context.Context, *CheckGroupAddModeRequest) (*CheckGroupAddModeResponse, error)
	GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GetGroupInfoResponse, error)
	GetGroupInfoList(context.Context, *emptypb.Empty) (*GetGroupInfoListResponse, error)
	GetGroupMemberList(context.Context, *GetGroupMemberListRequest) (*GetGroupMemberListResponse, error)
	mustEmbedUnimplementedGroupQueryServiceServer()
}

// UnimplementedGroupQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupQueryServiceServer struct{}

func (UnimplementedGroupQueryServiceServer) LoadMyGroup(context.Context, *LoadMyGroupRequest) (*LoadMyGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadMyGroup not implemented")
}
func (UnimplementedGroupQueryServiceServer) CheckGroupAddMode(context.Context, *CheckGroupAddModeRequest) (*CheckGroupAddModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckGroupAddMode not implemented")
}
func (UnimplementedGroupQueryServiceServer) GetGroupInfo(context.Context, *GetGroupInfoRequest) (*GetGroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedGroupQueryServiceServer) GetGroupInfoList(context.Context, *emptypb.Empty) (*GetGroupInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfoList not implemented")
}
func (UnimplementedGroupQueryServiceServer) GetGroupMemberList(context.Context, *GetGroupMemberListRequest) (*GetGroupMemberListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMemberList not implemented")
}
func (UnimplementedGroupQueryServiceServer) mustEmbedUnimplementedGroupQueryServiceServer() {}
func (UnimplementedGroupQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeGroupQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupQueryServiceServer will
// result in compilation errors.
type UnsafeGroupQueryServiceServer interface {
	mustEmbedUnimplementedGroupQueryServiceServer()
}

func RegisterGroupQueryServiceServer(s grpc.ServiceRegistrar, srv GroupQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedGroupQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupQueryService_ServiceDesc, srv)
}

func _GroupQueryService_LoadMyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupQueryServiceServer).LoadMyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupQueryService_LoadMyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupQueryServiceServer).LoadMyGroup(ctx, req.(*LoadMyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupQueryService_CheckGroupAddMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckGroupAddModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupQueryServiceServer).CheckGroupAddMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupQueryService_CheckGroupAddMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupQueryServiceServer).CheckGroupAddMode(ctx, req.(*CheckGroupAddModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupQueryService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupQueryServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupQueryService_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupQueryServiceServer).GetGroupInfo(ctx, req.(*GetGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupQueryService_GetGroupInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupQueryServiceServer).GetGroupInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupQueryService_GetGroupInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupQueryServiceServer).GetGroupInfoList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupQueryService_GetGroupMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupQueryServiceServer).GetGroupMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupQueryService_GetGroupMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupQueryServiceServer).GetGroupMemberList(ctx, req.(*GetGroupMemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupQueryService_ServiceDesc is the grpc.ServiceDesc for GroupQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.GroupQueryService",
	HandlerType: (*GroupQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadMyGroup",
			Handler:    _GroupQueryService_LoadMyGroup_Handler,
		},
		{
			MethodName: "CheckGroupAddMode",
			Handler:    _GroupQueryService_CheckGroupAddMode_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _GroupQueryService_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupInfoList",
			Handler:    _GroupQueryService_GetGroupInfoList_Handler,
		},
		{
			MethodName: "GetGroupMemberList",
			Handler:    _GroupQueryService_GetGroupMemberList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/group_query.proto",
}
