// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: query/group_query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadMyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMyGroupRequest) Reset() {
	*x = LoadMyGroupRequest{}
	mi := &file_query_group_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMyGroupRequest) ProtoMessage() {}

func (x *LoadMyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMyGroupRequest.ProtoReflect.Descriptor instead.
func (*LoadMyGroupRequest) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{0}
}

func (x *LoadMyGroupRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CheckGroupAddModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupAddModeRequest) Reset() {
	*x = CheckGroupAddModeRequest{}
	mi := &file_query_group_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupAddModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupAddModeRequest) ProtoMessage() {}

func (x *CheckGroupAddModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupAddModeRequest.ProtoReflect.Descriptor instead.
func (*CheckGroupAddModeRequest) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{1}
}

func (x *CheckGroupAddModeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_query_group_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupInfoRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetGroupMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListRequest) Reset() {
	*x = GetGroupMemberListRequest{}
	mi := &file_query_group_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListRequest) ProtoMessage() {}

func (x *GetGroupMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListRequest) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupMemberListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type MyGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyGroupItem) Reset() {
	*x = MyGroupItem{}
	mi := &file_query_group_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyGroupItem) ProtoMessage() {}

func (x *MyGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyGroupItem.ProtoReflect.Descriptor instead.
func (*MyGroupItem) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{4}
}

func (x *MyGroupItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MyGroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *MyGroupItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type LoadMyGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*MyGroupItem         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMyGroupResponse) Reset() {
	*x = LoadMyGroupResponse{}
	mi := &file_query_group_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMyGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMyGroupResponse) ProtoMessage() {}

func (x *LoadMyGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMyGroupResponse.ProtoReflect.Descriptor instead.
func (*LoadMyGroupResponse) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{5}
}

func (x *LoadMyGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadMyGroupResponse) GetList() []*MyGroupItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *LoadMyGroupResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type CheckGroupAddModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AddMode       int32                  `protobuf:"varint,2,opt,name=add_mode,json=addMode,proto3" json:"add_mode,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupAddModeResponse) Reset() {
	*x = CheckGroupAddModeResponse{}
	mi := &file_query_group_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupAddModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupAddModeResponse) ProtoMessage() {}

func (x *CheckGroupAddModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupAddModeResponse.ProtoReflect.Descriptor instead.
func (*CheckGroupAddModeResponse) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{6}
}

func (x *CheckGroupAddModeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckGroupAddModeResponse) GetAddMode() int32 {
	if x != nil {
		return x.AddMode
	}
	return 0
}

func (x *CheckGroupAddModeResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GroupInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notice        string                 `protobuf:"bytes,3,opt,name=notice,proto3" json:"notice,omitempty"`
	MemberCnt     int32                  `protobuf:"varint,4,opt,name=member_cnt,json=memberCnt,proto3" json:"member_cnt,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AddMode       int32                  `protobuf:"varint,6,opt,name=add_mode,json=addMode,proto3" json:"add_mode,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoDetail) Reset() {
	*x = GroupInfoDetail{}
	mi := &file_query_group_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoDetail) ProtoMessage() {}

func (x *GroupInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoDetail.ProtoReflect.Descriptor instead.
func (*GroupInfoDetail) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{7}
}

func (x *GroupInfoDetail) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GroupInfoDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfoDetail) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *GroupInfoDetail) GetMemberCnt() int32 {
	if x != nil {
		return x.MemberCnt
	}
	return 0
}

func (x *GroupInfoDetail) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GroupInfoDetail) GetAddMode() int32 {
	if x != nil {
		return x.AddMode
	}
	return 0
}

func (x *GroupInfoDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupInfoDetail) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupInfoDetail) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type GetGroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Info          *GroupInfoDetail       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResponse) Reset() {
	*x = GetGroupInfoResponse{}
	mi := &file_query_group_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResponse) ProtoMessage() {}

func (x *GetGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{8}
}

func (x *GetGroupInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupInfoResponse) GetInfo() *GroupInfoDetail {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetGroupInfoResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GroupListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListItem) Reset() {
	*x = GroupListItem{}
	mi := &file_query_group_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListItem) ProtoMessage() {}

func (x *GroupListItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListItem.ProtoReflect.Descriptor instead.
func (*GroupListItem) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{9}
}

func (x *GroupListItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GroupListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupListItem) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GroupListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupListItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type GetGroupInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*GroupListItem       `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoListResponse) Reset() {
	*x = GetGroupInfoListResponse{}
	mi := &file_query_group_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoListResponse) ProtoMessage() {}

func (x *GetGroupInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupInfoListResponse) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupInfoListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupInfoListResponse) GetList() []*GroupListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupInfoListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GroupMemberItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberItem) Reset() {
	*x = GroupMemberItem{}
	mi := &file_query_group_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberItem) ProtoMessage() {}

func (x *GroupMemberItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberItem.ProtoReflect.Descriptor instead.
func (*GroupMemberItem) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{11}
}

func (x *GroupMemberItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMemberItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMemberItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetGroupMemberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*GroupMemberItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListResponse) Reset() {
	*x = GetGroupMemberListResponse{}
	mi := &file_query_group_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListResponse) ProtoMessage() {}

func (x *GetGroupMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_group_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListResponse) Descriptor() ([]byte, []int) {
	return file_query_group_query_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupMemberListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupMemberListResponse) GetList() []*GroupMemberItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupMemberListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_query_group_query_proto protoreflect.FileDescriptor

const file_query_group_query_proto_rawDesc = "" +
	"\n" +
	"\x17query/group_query.proto\x12\x05query\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x12LoadMyGroupRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"5\n" +
	"\x18CheckGroupAddModeRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"0\n" +
	"\x13GetGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"6\n" +
	"\x19GetGroupMemberListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"_\n" +
	"\vMyGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"i\n" +
	"\x13LoadMyGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.query.MyGroupItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"b\n" +
	"\x19CheckGroupAddModeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\badd_mode\x18\x02 \x01(\x05R\aaddMode\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\xf5\x01\n" +
	"\x0fGroupInfoDetail\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06notice\x18\x03 \x01(\tR\x06notice\x12\x1d\n" +
	"\n" +
	"member_cnt\x18\x04 \x01(\x05R\tmemberCnt\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x19\n" +
	"\badd_mode\x18\x06 \x01(\x05R\aaddMode\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\"n\n" +
	"\x14GetGroupInfoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x04info\x18\x02 \x01(\v2\x16.query.GroupInfoDetailR\x04info\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\x89\x01\n" +
	"\rGroupListItem\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\"p\n" +
	"\x18GetGroupInfoListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12(\n" +
	"\x04list\x18\x02 \x03(\v2\x14.query.GroupListItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"^\n" +
	"\x0fGroupMemberItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"t\n" +
	"\x1aGetGroupMemberListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.query.GroupMemberItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret2\xa2\x03\n" +
	"\x11GroupQueryService\x12D\n" +
	"\vLoadMyGroup\x12\x19.query.LoadMyGroupRequest\x1a\x1a.query.LoadMyGroupResponse\x12V\n" +
	"\x11CheckGroupAddMode\x12\x1f.query.CheckGroupAddModeRequest\x1a .query.CheckGroupAddModeResponse\x12G\n" +
	"\fGetGroupInfo\x12\x1a.query.GetGroupInfoRequest\x1a\x1b.query.GetGroupInfoResponse\x12K\n" +
	"\x10GetGroupInfoList\x12\x16.google.protobuf.Empty\x1a\x1f.query.GetGroupInfoListResponse\x12Y\n" +
	"\x12GetGroupMemberList\x12 .query.GetGroupMemberListRequest\x1a!.query.GetGroupMemberListResponseB\x1eZ\x1ckama_chat_server/proto/queryb\x06proto3"

var (
	file_query_group_query_proto_rawDescOnce sync.Once
	file_query_group_query_proto_rawDescData []byte
)

func file_query_group_query_proto_rawDescGZIP() []byte {
	file_query_group_query_proto_rawDescOnce.Do(func() {
		file_query_group_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_group_query_proto_rawDesc), len(file_query_group_query_proto_rawDesc)))
	})
	return file_query_group_query_proto_rawDescData
}

var file_query_group_query_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_query_group_query_proto_goTypes = []any{
	(*LoadMyGroupRequest)(nil),         // 0: query.LoadMyGroupRequest
	(*CheckGroupAddModeRequest)(nil),   // 1: query.CheckGroupAddModeRequest
	(*GetGroupInfoRequest)(nil),        // 2: query.GetGroupInfoRequest
	(*GetGroupMemberListRequest)(nil),  // 3: query.GetGroupMemberListRequest
	(*MyGroupItem)(nil),                // 4: query.MyGroupItem
	(*LoadMyGroupResponse)(nil),        // 5: query.LoadMyGroupResponse
	(*CheckGroupAddModeResponse)(nil),  // 6: query.CheckGroupAddModeResponse
	(*GroupInfoDetail)(nil),            // 7: query.GroupInfoDetail
	(*GetGroupInfoResponse)(nil),       // 8: query.GetGroupInfoResponse
	(*GroupListItem)(nil),              // 9: query.GroupListItem
	(*GetGroupInfoListResponse)(nil),   // 10: query.GetGroupInfoListResponse
	(*GroupMemberItem)(nil),            // 11: query.GroupMemberItem
	(*GetGroupMemberListResponse)(nil), // 12: query.GetGroupMemberListResponse
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_query_group_query_proto_depIdxs = []int32{
	4,  // 0: query.LoadMyGroupResponse.list:type_name -> query.MyGroupItem
	7,  // 1: query.GetGroupInfoResponse.info:type_name -> query.GroupInfoDetail
	9,  // 2: query.GetGroupInfoListResponse.list:type_name -> query.GroupListItem
	11, // 3: query.GetGroupMemberListResponse.list:type_name -> query.GroupMemberItem
	0,  // 4: query.GroupQueryService.LoadMyGroup:input_type -> query.LoadMyGroupRequest
	1,  // 5: query.GroupQueryService.CheckGroupAddMode:input_type -> query.CheckGroupAddModeRequest
	2,  // 6: query.GroupQueryService.GetGroupInfo:input_type -> query.GetGroupInfoRequest
	13, // 7: query.GroupQueryService.GetGroupInfoList:input_type -> google.protobuf.Empty
	3,  // 8: query.GroupQueryService.GetGroupMemberList:input_type -> query.GetGroupMemberListRequest
	5,  // 9: query.GroupQueryService.LoadMyGroup:output_type -> query.LoadMyGroupResponse
	6,  // 10: query.GroupQueryService.CheckGroupAddMode:output_type -> query.CheckGroupAddModeResponse
	8,  // 11: query.GroupQueryService.GetGroupInfo:output_type -> query.GetGroupInfoResponse
	10, // 12: query.GroupQueryService.GetGroupInfoList:output_type -> query.GetGroupInfoListResponse
	12, // 13: query.GroupQueryService.GetGroupMemberList:output_type -> query.GetGroupMemberListResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_query_group_query_proto_init() }
func file_query_group_query_proto_init() {
	if File_query_group_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_group_query_proto_rawDesc), len(file_query_group_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_group_query_proto_goTypes,
		DependencyIndexes: file_query_group_query_proto_depIdxs,
		MessageInfos:      file_query_group_query_proto_msgTypes,
	}.Build()
	File_query_group_query_proto = out.File
	file_query_group_query_proto_goTypes = nil
	file_query_group_query_proto_depIdxs = nil
}
