// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: query/message_query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserOneId     string                 `protobuf:"bytes,1,opt,name=user_one_id,json=userOneId,proto3" json:"user_one_id,omitempty"`
	UserTwoId     string                 `protobuf:"bytes,2,opt,name=user_two_id,json=userTwoId,proto3" json:"user_two_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListRequest) Reset() {
	*x = GetMessageListRequest{}
	mi := &file_query_message_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListRequest) ProtoMessage() {}

func (x *GetMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetMessageListRequest) Descriptor() ([]byte, []int) {
	return file_query_message_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageListRequest) GetUserOneId() string {
	if x != nil {
		return x.UserOneId
	}
	return ""
}

func (x *GetMessageListRequest) GetUserTwoId() string {
	if x != nil {
		return x.UserTwoId
	}
	return ""
}

type GetGroupMessageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMessageListRequest) Reset() {
	*x = GetGroupMessageListRequest{}
	mi := &file_query_message_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMessageListRequest) ProtoMessage() {}

func (x *GetGroupMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMessageListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMessageListRequest) Descriptor() ([]byte, []int) {
	return file_query_message_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupMessageListRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendId        string                 `protobuf:"bytes,1,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`
	SendName      string                 `protobuf:"bytes,2,opt,name=send_name,json=sendName,proto3" json:"send_name,omitempty"`
	SendAvatar    string                 `protobuf:"bytes,3,opt,name=send_avatar,json=sendAvatar,proto3" json:"send_avatar,omitempty"`
	ReceiveId     string                 `protobuf:"bytes,4,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	FileType      string                 `protobuf:"bytes,8,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileName      string                 `protobuf:"bytes,9,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      string                 `protobuf:"bytes,10,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_query_message_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_query_message_query_proto_rawDescGZIP(), []int{2}
}

func (x *MessageItem) GetSendId() string {
	if x != nil {
		return x.SendId
	}
	return ""
}

func (x *MessageItem) GetSendName() string {
	if x != nil {
		return x.SendName
	}
	return ""
}

func (x *MessageItem) GetSendAvatar() string {
	if x != nil {
		return x.SendAvatar
	}
	return ""
}

func (x *MessageItem) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *MessageItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageItem) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *MessageItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MessageItem) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *MessageItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetMessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*MessageItem         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListResponse) Reset() {
	*x = GetMessageListResponse{}
	mi := &file_query_message_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListResponse) ProtoMessage() {}

func (x *GetMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListResponse.ProtoReflect.Descriptor instead.
func (*GetMessageListResponse) Descriptor() ([]byte, []int) {
	return file_query_message_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMessageListResponse) GetList() []*MessageItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetMessageListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GetGroupMessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*MessageItem         `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMessageListResponse) Reset() {
	*x = GetGroupMessageListResponse{}
	mi := &file_query_message_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMessageListResponse) ProtoMessage() {}

func (x *GetGroupMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMessageListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMessageListResponse) Descriptor() ([]byte, []int) {
	return file_query_message_query_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupMessageListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupMessageListResponse) GetList() []*MessageItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetGroupMessageListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_query_message_query_proto protoreflect.FileDescriptor

const file_query_message_query_proto_rawDesc = "" +
	"\n" +
	"\x19query/message_query.proto\x12\x05query\"W\n" +
	"\x15GetMessageListRequest\x12\x1e\n" +
	"\vuser_one_id\x18\x01 \x01(\tR\tuserOneId\x12\x1e\n" +
	"\vuser_two_id\x18\x02 \x01(\tR\tuserTwoId\"7\n" +
	"\x1aGetGroupMessageListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\xb9\x02\n" +
	"\vMessageItem\x12\x17\n" +
	"\asend_id\x18\x01 \x01(\tR\x06sendId\x12\x1b\n" +
	"\tsend_name\x18\x02 \x01(\tR\bsendName\x12\x1f\n" +
	"\vsend_avatar\x18\x03 \x01(\tR\n" +
	"sendAvatar\x12\x1d\n" +
	"\n" +
	"receive_id\x18\x04 \x01(\tR\treceiveId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_type\x18\b \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_name\x18\t \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\n" +
	" \x01(\tR\bfileSize\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"l\n" +
	"\x16GetMessageListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.query.MessageItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"q\n" +
	"\x1bGetGroupMessageListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.query.MessageItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret2\xc2\x01\n" +
	"\x13MessageQueryService\x12M\n" +
	"\x0eGetMessageList\x12\x1c.query.GetMessageListRequest\x1a\x1d.query.GetMessageListResponse\x12\\\n" +
	"\x13GetGroupMessageList\x12!.query.GetGroupMessageListRequest\x1a\".query.GetGroupMessageListResponseB\x1eZ\x1ckama_chat_server/proto/queryb\x06proto3"

var (
	file_query_message_query_proto_rawDescOnce sync.Once
	file_query_message_query_proto_rawDescData []byte
)

func file_query_message_query_proto_rawDescGZIP() []byte {
	file_query_message_query_proto_rawDescOnce.Do(func() {
		file_query_message_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_message_query_proto_rawDesc), len(file_query_message_query_proto_rawDesc)))
	})
	return file_query_message_query_proto_rawDescData
}

var file_query_message_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_query_message_query_proto_goTypes = []any{
	(*GetMessageListRequest)(nil),       // 0: query.GetMessageListRequest
	(*GetGroupMessageListRequest)(nil),  // 1: query.GetGroupMessageListRequest
	(*MessageItem)(nil),                 // 2: query.MessageItem
	(*GetMessageListResponse)(nil),      // 3: query.GetMessageListResponse
	(*GetGroupMessageListResponse)(nil), // 4: query.GetGroupMessageListResponse
}
var file_query_message_query_proto_depIdxs = []int32{
	2, // 0: query.GetMessageListResponse.list:type_name -> query.MessageItem
	2, // 1: query.GetGroupMessageListResponse.list:type_name -> query.MessageItem
	0, // 2: query.MessageQueryService.GetMessageList:input_type -> query.GetMessageListRequest
	1, // 3: query.MessageQueryService.GetGroupMessageList:input_type -> query.GetGroupMessageListRequest
	3, // 4: query.MessageQueryService.GetMessageList:output_type -> query.GetMessageListResponse
	4, // 5: query.MessageQueryService.GetGroupMessageList:output_type -> query.GetGroupMessageListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_message_query_proto_init() }
func file_query_message_query_proto_init() {
	if File_query_message_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_message_query_proto_rawDesc), len(file_query_message_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_message_query_proto_goTypes,
		DependencyIndexes: file_query_message_query_proto_depIdxs,
		MessageInfos:      file_query_message_query_proto_msgTypes,
	}.Build()
	File_query_message_query_proto = out.File
	file_query_message_query_proto_goTypes = nil
	file_query_message_query_proto_depIdxs = nil
}
