// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: query/message_query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageQueryService_GetMessageList_FullMethodName      = "/query.MessageQueryService/GetMessageList"
	MessageQueryService_GetGroupMessageList_FullMethodName = "/query.MessageQueryService/GetGroupMessageList"
)

// MessageQueryServiceClient is the client API for MessageQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageQueryServiceClient interface {
	GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error)
	GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*GetGroupMessageListResponse, error)
}

type messageQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueryServiceClient(cc grpc.ClientConnInterface) MessageQueryServiceClient {
	return &messageQueryServiceClient{cc}
}

func (c *messageQueryServiceClient) GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageListResponse)
	err := c.cc.Invoke(ctx, MessageQueryService_GetMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageQueryServiceClient) GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*GetGroupMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMessageListResponse)
	err := c.cc.Invoke(ctx, MessageQueryService_GetGroupMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageQueryServiceServer is the server API for MessageQueryService service.
// All implementations must embed UnimplementedMessageQueryServiceServer
// for forward compatibility.
type MessageQueryServiceServer interface {
	GetMessageList(context.Context, *GetMessageListRequest) (*GetMessageListResponse, error)
	GetGroupMessageList(context.Context, *GetGroupMessageListRequest) (*GetGroupMessageListResponse, error)
	mustEmbedUnimplementedMessageQueryServiceServer()
}

// UnimplementedMessageQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageQueryServiceServer struct{}

func (UnimplementedMessageQueryServiceServer) GetMessageList(context.Context, *GetMessageListRequest) (*GetMessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageList not implemented")
}
func (UnimplementedMessageQueryServiceServer) GetGroupMessageList(context.Context, *GetGroupMessageListRequest) (*GetGroupMessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMessageList not implemented")
}
func (UnimplementedMessageQueryServiceServer) mustEmbedUnimplementedMessageQueryServiceServer() {}
func (UnimplementedMessageQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeMessageQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueryServiceServer will
// result in compilation errors.
type UnsafeMessageQueryServiceServer interface {
	mustEmbedUnimplementedMessageQueryServiceServer()
}

func RegisterMessageQueryServiceServer(s grpc.ServiceRegistrar, srv MessageQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageQueryService_ServiceDesc, srv)
}

func _MessageQueryService_GetMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueryServiceServer).GetMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueryService_GetMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueryServiceServer).GetMessageList(ctx, req.(*GetMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageQueryService_GetGroupMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueryServiceServer).GetGroupMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageQueryService_GetGroupMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueryServiceServer).GetGroupMessageList(ctx, req.(*GetGroupMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageQueryService_ServiceDesc is the grpc.ServiceDesc for MessageQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.MessageQueryService",
	HandlerType: (*MessageQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessageList",
			Handler:    _MessageQueryService_GetMessageList_Handler,
		},
		{
			MethodName: "GetGroupMessageList",
			Handler:    _MessageQueryService_GetGroupMessageList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/message_query.proto",
}
