// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: query/session_query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionListRequest) Reset() {
	*x = GetSessionListRequest{}
	mi := &file_query_session_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionListRequest) ProtoMessage() {}

func (x *GetSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_session_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionListRequest.ProtoReflect.Descriptor instead.
func (*GetSessionListRequest) Descriptor() ([]byte, []int) {
	return file_query_session_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionListRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UserSessionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionItem) Reset() {
	*x = UserSessionItem{}
	mi := &file_query_session_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionItem) ProtoMessage() {}

func (x *UserSessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_session_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionItem.ProtoReflect.Descriptor instead.
func (*UserSessionItem) Descriptor() ([]byte, []int) {
	return file_query_session_query_proto_rawDescGZIP(), []int{1}
}

func (x *UserSessionItem) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserSessionItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSessionItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSessionItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UserSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*UserSessionItem     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionListResponse) Reset() {
	*x = UserSessionListResponse{}
	mi := &file_query_session_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionListResponse) ProtoMessage() {}

func (x *UserSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_session_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionListResponse.ProtoReflect.Descriptor instead.
func (*UserSessionListResponse) Descriptor() ([]byte, []int) {
	return file_query_session_query_proto_rawDescGZIP(), []int{2}
}

func (x *UserSessionListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserSessionListResponse) GetList() []*UserSessionItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *UserSessionListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GroupSessionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupId       string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSessionItem) Reset() {
	*x = GroupSessionItem{}
	mi := &file_query_session_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSessionItem) ProtoMessage() {}

func (x *GroupSessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_session_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSessionItem.ProtoReflect.Descriptor instead.
func (*GroupSessionItem) Descriptor() ([]byte, []int) {
	return file_query_session_query_proto_rawDescGZIP(), []int{3}
}

func (x *GroupSessionItem) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GroupSessionItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupSessionItem) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupSessionItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GroupSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*GroupSessionItem    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSessionListResponse) Reset() {
	*x = GroupSessionListResponse{}
	mi := &file_query_session_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSessionListResponse) ProtoMessage() {}

func (x *GroupSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_session_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSessionListResponse.ProtoReflect.Descriptor instead.
func (*GroupSessionListResponse) Descriptor() ([]byte, []int) {
	return file_query_session_query_proto_rawDescGZIP(), []int{4}
}

func (x *GroupSessionListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupSessionListResponse) GetList() []*GroupSessionItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GroupSessionListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_query_session_query_proto protoreflect.FileDescriptor

const file_query_session_query_proto_rawDesc = "" +
	"\n" +
	"\x19query/session_query.proto\x12\x05query\"2\n" +
	"\x15GetSessionListRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"~\n" +
	"\x0fUserSessionItem\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\"q\n" +
	"\x17UserSessionListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.query.UserSessionItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\x83\x01\n" +
	"\x10GroupSessionItem\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"s\n" +
	"\x18GroupSessionListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12+\n" +
	"\x04list\x18\x02 \x03(\v2\x17.query.GroupSessionItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret2\xbf\x01\n" +
	"\x13SessionQueryService\x12R\n" +
	"\x12GetUserSessionList\x12\x1c.query.GetSessionListRequest\x1a\x1e.query.UserSessionListResponse\x12T\n" +
	"\x13GetGroupSessionList\x12\x1c.query.GetSessionListRequest\x1a\x1f.query.GroupSessionListResponseB\x1eZ\x1ckama_chat_server/proto/queryb\x06proto3"

var (
	file_query_session_query_proto_rawDescOnce sync.Once
	file_query_session_query_proto_rawDescData []byte
)

func file_query_session_query_proto_rawDescGZIP() []byte {
	file_query_session_query_proto_rawDescOnce.Do(func() {
		file_query_session_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_session_query_proto_rawDesc), len(file_query_session_query_proto_rawDesc)))
	})
	return file_query_session_query_proto_rawDescData
}

var file_query_session_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_query_session_query_proto_goTypes = []any{
	(*GetSessionListRequest)(nil),    // 0: query.GetSessionListRequest
	(*UserSessionItem)(nil),          // 1: query.UserSessionItem
	(*UserSessionListResponse)(nil),  // 2: query.UserSessionListResponse
	(*GroupSessionItem)(nil),         // 3: query.GroupSessionItem
	(*GroupSessionListResponse)(nil), // 4: query.GroupSessionListResponse
}
var file_query_session_query_proto_depIdxs = []int32{
	1, // 0: query.UserSessionListResponse.list:type_name -> query.UserSessionItem
	3, // 1: query.GroupSessionListResponse.list:type_name -> query.GroupSessionItem
	0, // 2: query.SessionQueryService.GetUserSessionList:input_type -> query.GetSessionListRequest
	0, // 3: query.SessionQueryService.GetGroupSessionList:input_type -> query.GetSessionListRequest
	2, // 4: query.SessionQueryService.GetUserSessionList:output_type -> query.UserSessionListResponse
	4, // 5: query.SessionQueryService.GetGroupSessionList:output_type -> query.GroupSessionListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_session_query_proto_init() }
func file_query_session_query_proto_init() {
	if File_query_session_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_session_query_proto_rawDesc), len(file_query_session_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_session_query_proto_goTypes,
		DependencyIndexes: file_query_session_query_proto_depIdxs,
		MessageInfos:      file_query_session_query_proto_msgTypes,
	}.Build()
	File_query_session_query_proto = out.File
	file_query_session_query_proto_goTypes = nil
	file_query_session_query_proto_depIdxs = nil
}
