// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: query/session_query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionQueryService_GetUserSessionList_FullMethodName  = "/query.SessionQueryService/GetUserSessionList"
	SessionQueryService_GetGroupSessionList_FullMethodName = "/query.SessionQueryService/GetGroupSessionList"
)

// SessionQueryServiceClient is the client API for SessionQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionQueryServiceClient interface {
	GetUserSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*UserSessionListResponse, error)
	GetGroupSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GroupSessionListResponse, error)
}

type sessionQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionQueryServiceClient(cc grpc.ClientConnInterface) SessionQueryServiceClient {
	return &sessionQueryServiceClient{cc}
}

func (c *sessionQueryServiceClient) GetUserSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*UserSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSessionListResponse)
	err := c.cc.Invoke(ctx, SessionQueryService_GetUserSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionQueryServiceClient) GetGroupSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GroupSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupSessionListResponse)
	err := c.cc.Invoke(ctx, SessionQueryService_GetGroupSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionQueryServiceServer is the server API for SessionQueryService service.
// All implementations must embed UnimplementedSessionQueryServiceServer
// for forward compatibility.
type SessionQueryServiceServer interface {
	GetUserSessionList(context.Context, *GetSessionListRequest) (*UserSessionListResponse, error)
	GetGroupSessionList(context.Context, *GetSessionListRequest) (*GroupSessionListResponse, error)
	mustEmbedUnimplementedSessionQueryServiceServer()
}

// UnimplementedSessionQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionQueryServiceServer struct{}

func (UnimplementedSessionQueryServiceServer) GetUserSessionList(context.Context, *GetSessionListRequest) (*UserSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSessionList not implemented")
}
func (UnimplementedSessionQueryServiceServer) GetGroupSessionList(context.Context, *GetSessionListRequest) (*GroupSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupSessionList not implemented")
}
func (UnimplementedSessionQueryServiceServer) mustEmbedUnimplementedSessionQueryServiceServer() {}
func (UnimplementedSessionQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeSessionQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionQueryServiceServer will
// result in compilation errors.
type UnsafeSessionQueryServiceServer interface {
	mustEmbedUnimplementedSessionQueryServiceServer()
}

func RegisterSessionQueryServiceServer(s grpc.ServiceRegistrar, srv SessionQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionQueryService_ServiceDesc, srv)
}

func _SessionQueryService_GetUserSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServiceServer).GetUserSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQueryService_GetUserSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServiceServer).GetUserSessionList(ctx, req.(*GetSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionQueryService_GetGroupSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionQueryServiceServer).GetGroupSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionQueryService_GetGroupSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionQueryServiceServer).GetGroupSessionList(ctx, req.(*GetSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionQueryService_ServiceDesc is the grpc.ServiceDesc for SessionQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.SessionQueryService",
	HandlerType: (*SessionQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSessionList",
			Handler:    _SessionQueryService_GetUserSessionList_Handler,
		},
		{
			MethodName: "GetGroupSessionList",
			Handler:    _SessionQueryService_GetGroupSessionList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/session_query.proto",
}
