// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: query/user_query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoListRequest) Reset() {
	*x = GetUserInfoListRequest{}
	mi := &file_query_user_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoListRequest) ProtoMessage() {}

func (x *GetUserInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoListRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoListRequest) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoListRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_query_user_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type UserListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Telephone     string                 `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	IsAdmin       int32                  `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListItem) Reset() {
	*x = UserListItem{}
	mi := &file_query_user_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListItem) ProtoMessage() {}

func (x *UserListItem) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListItem.ProtoReflect.Descriptor instead.
func (*UserListItem) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{2}
}

func (x *UserListItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserListItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserListItem) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UserListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserListItem) GetIsAdmin() int32 {
	if x != nil {
		return x.IsAdmin
	}
	return 0
}

func (x *UserListItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type GetUserInfoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	List          []*UserListItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoListResponse) Reset() {
	*x = GetUserInfoListResponse{}
	mi := &file_query_user_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoListResponse) ProtoMessage() {}

func (x *GetUserInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoListResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoListResponse) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserInfoListResponse) GetList() []*UserListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserInfoListResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type UserInfoDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Telephone     string                 `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday      string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAdmin       int32                  `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoDetail) Reset() {
	*x = UserInfoDetail{}
	mi := &file_query_user_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoDetail) ProtoMessage() {}

func (x *UserInfoDetail) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoDetail.ProtoReflect.Descriptor instead.
func (*UserInfoDetail) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoDetail) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserInfoDetail) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoDetail) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UserInfoDetail) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoDetail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoDetail) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfoDetail) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserInfoDetail) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserInfoDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfoDetail) GetIsAdmin() int32 {
	if x != nil {
		return x.IsAdmin
	}
	return 0
}

func (x *UserInfoDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Info          *UserInfoDetail        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Ret           int32                  `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_query_user_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_user_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_query_user_query_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserInfoResponse) GetInfo() *UserInfoDetail {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetUserInfoResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

var File_query_user_query_proto protoreflect.FileDescriptor

const file_query_user_query_proto_rawDesc = "" +
	"\n" +
	"\x16query/user_query.proto\x12\x05query\"3\n" +
	"\x16GetUserInfoListRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"(\n" +
	"\x12GetUserInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xae\x01\n" +
	"\fUserListItem\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttelephone\x18\x03 \x01(\tR\ttelephone\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\x05R\aisAdmin\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\"n\n" +
	"\x17GetUserInfoListResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x04list\x18\x02 \x03(\v2\x13.query.UserListItemR\x04list\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret\"\xb0\x02\n" +
	"\x0eUserInfoDetail\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttelephone\x18\x03 \x01(\tR\ttelephone\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bis_admin\x18\n" +
	" \x01(\x05R\aisAdmin\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"l\n" +
	"\x13GetUserInfoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x04info\x18\x02 \x01(\v2\x15.query.UserInfoDetailR\x04info\x12\x10\n" +
	"\x03ret\x18\x03 \x01(\x05R\x03ret2\xaa\x01\n" +
	"\x10UserQueryService\x12P\n" +
	"\x0fGetUserInfoList\x12\x1d.query.GetUserInfoListRequest\x1a\x1e.query.GetUserInfoListResponse\x12D\n" +
	"\vGetUserInfo\x12\x19.query.GetUserInfoRequest\x1a\x1a.query.GetUserInfoResponseB\x1eZ\x1ckama_chat_server/proto/queryb\x06proto3"

var (
	file_query_user_query_proto_rawDescOnce sync.Once
	file_query_user_query_proto_rawDescData []byte
)

func file_query_user_query_proto_rawDescGZIP() []byte {
	file_query_user_query_proto_rawDescOnce.Do(func() {
		file_query_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_user_query_proto_rawDesc), len(file_query_user_query_proto_rawDesc)))
	})
	return file_query_user_query_proto_rawDescData
}

var file_query_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_user_query_proto_goTypes = []any{
	(*GetUserInfoListRequest)(nil),  // 0: query.GetUserInfoListRequest
	(*GetUserInfoRequest)(nil),      // 1: query.GetUserInfoRequest
	(*UserListItem)(nil),            // 2: query.UserListItem
	(*GetUserInfoListResponse)(nil), // 3: query.GetUserInfoListResponse
	(*UserInfoDetail)(nil),          // 4: query.UserInfoDetail
	(*GetUserInfoResponse)(nil),     // 5: query.GetUserInfoResponse
}
var file_query_user_query_proto_depIdxs = []int32{
	2, // 0: query.GetUserInfoListResponse.list:type_name -> query.UserListItem
	4, // 1: query.GetUserInfoResponse.info:type_name -> query.UserInfoDetail
	0, // 2: query.UserQueryService.GetUserInfoList:input_type -> query.GetUserInfoListRequest
	1, // 3: query.UserQueryService.GetUserInfo:input_type -> query.GetUserInfoRequest
	3, // 4: query.UserQueryService.GetUserInfoList:output_type -> query.GetUserInfoListResponse
	5, // 5: query.UserQueryService.GetUserInfo:output_type -> query.GetUserInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_user_query_proto_init() }
func file_query_user_query_proto_init() {
	if File_query_user_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_user_query_proto_rawDesc), len(file_query_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_user_query_proto_goTypes,
		DependencyIndexes: file_query_user_query_proto_depIdxs,
		MessageInfos:      file_query_user_query_proto_msgTypes,
	}.Build()
	File_query_user_query_proto = out.File
	file_query_user_query_proto_goTypes = nil
	file_query_user_query_proto_depIdxs = nil
}
